# Generated by Django 3.1.7 on 2023-12-07 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0002_auto_20231115_2236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opportunity',
            old_name='completed',
            new_name='is_remote',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='completed_date',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='paid',
        ),
        migrations.AddField(
            model_name='opportunity',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opportunity',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='salary_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='salary_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
