# Generated by Django 3.1.7 on 2023-03-11 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0003_auto_20230308_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('Hackathon', 'Hackathon'), ('Tech Talk', 'Tech Talk'), ('Research', 'Research'), ('Class', 'Class'), ('Workshop', 'Workshop'), ('Other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('Research', 'Research'), ('Independent Study', 'Independent Study'), ('SIP', 'SIP'), ('Honors Thesis', 'Honors Thesis'), ('Other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='resource',
            name='category',
            field=models.CharField(choices=[('Resume', 'Resume'), ('CV', 'CV'), ('Cover Letter', 'Cover Letter'), ('Masters', 'Masters'), ('PhD', 'PhD'), ('Other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Student', 'Student'), ('Alumni', 'Alumni'), ('Faculty', 'Faculty'), ('Admin', 'Admin'), ('Staff', 'Staff'), ('Other', 'Other')], default='Student', max_length=255),
        ),
    ]
